---
- name: ensure hpcusers group exists
  group:
    name: hpcusers
    state: present
    gid: 1050
  tags: users

- name: add geekohpc group
  group:
    name: geekohpc
    state: present
    gid: 1051
  tags: users

- name: add cluster user geekohpc
  user:
    name: geekohpc
    comment: Geeko HPC User
    uid: 1051
    group: 1051
    groups: hpcusers, users
    append: yes
    shell: /bin/bash
    home: /data/geekohpc
    create_home: false
  tags: users
