- name: install nfs client
  zypper:
    name: nfs-client
    state: present
  tags: nfs

- name: add nfs /etc/fstab entry
  lineinfile:
    path: /etc/fstab
    state: present
    line: '172.16.250.164:/data                       /data      nfs   defaults,vers=3,proto=tcp,nofail 0 0'
  tags: nfs

