- name: install nfs client
  zypper:
    name: nfs-client
    state: present
  tags: nfs

- name: mount nfs storage
  mount:
    path: /data
    src: 172.16.250.164:/export/data
    opts: defaults,vers=3,proto=tcp,nofail
    state: mounted
    fstype: nfs
  tags: nfs

