---
- name: install slurm manager packages
  zypper:
    name: "{{ slurm_mgr_rpms }}"
    state: present
  tags: slurm

# /etc/munge/munge.key needs to be the same across the cluster
# The munge key is currently not handled by ansible.
- name: start and enable munge
  service: 
    name: munge
    enabled: yes
    state: started
  tags: slurm

- name: install custom innodb.cfg
  template: 
    src: innodb.cnf.j2
    dest: /etc/my.cnf.d/innodb.cnf
    owner: root
    group: root
    mode: '0644'
  register: cnfchanged
  tags: slurm

- name: start and enable database
  service: 
    name: mariadb
    enabled: yes
    state: started
  tags: slurm

- name: restart database if cnf changed
  service: 
    name: mariadb
    state: restarted
  when: cnfchanged.changed
  tags: slurm

- name: start and enable slurmdbd
  service: 
    name: slurmdbd
    enabled: yes
    state: started
  tags: slurm

- name: configure slurm.conf
  template: 
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: root
    group: root
    mode: '0644'
  register: slurmchanged
  tags:
    - slurm
    - slurmconf

- name: start and enable slurmctld
  service: 
    name: slurmctld
    enabled: yes
    state: started
  tags: slurm

- name: reload slurm config
  service: 
    name: slurmctld
    enabled: yes
    state: restarted
  when: slurmchanged.changed
  tags:
    - slurm
    - slurmconf
