---
- name: install slurm node packages
  zypper:
    name: "{{ slurm_node_rpms }}"
    state: present
  tags: slurm

# /etc/munge/munge.key needs to be the same across the cluster
# The munge key is currently not handled by ansible.
- name: start and enable munge
  service: 
    name: munge
    enabled: yes
    state: started
  tags: slurm

- name: configure slurm.conf
  template: 
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: root
    group: root
    mode: '0644'
  register: slurmchanged
  tags:
    - slurm
    - slurmconf

- name: start and enable slurmd
  service: 
    name: slurmd
    enabled: yes
    state: started
  tags: slurm

- name: reload slurm config
  service: 
    name: slurmd
    enabled: yes
    state: restarted
  when: slurmchanged.changed
  tags:
    - slurm
    - slurmconf
