---
- name: ensure hpcusers group exists
  group:
    name: hpcusers
    state: present
    gid: 1050
  tags: users

- name: add geekohpc group
  group:
    name: geekohpc
    state: present
    gid: 1051
  tags: users

- name: add cluster user geekohpc
  user:
    name: geekohpc
    comment: Geeko HPC User
    uid: 1051
    group: 1051
    groups: hpcusers, users
    append: yes
    shell: /bin/bash
    home: /data/geekohpc
    create_home: true
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  tags: users

- name: set up authorized keys
  copy:
    src: /data/geekohpc/.ssh/id_rsa.pub
    dest: /data/geekohpc/.ssh/authorized_keys
    owner: geekohpc
    group: geekohpc
    mode: '0600'
    backup: yes
  tags: users
