- name: mount bind mount
  mount:
    path: /data
    src: /export/data
    opts: bind
    state: mounted
    fstype: none
  tags: nfs

- name: install nfs server
  zypper:
    name: nfs-kernel-server
    state: present
  tags: nfs

- name: setup /etc/exports
  template: 
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  register: exportschanged
  tags: nfs

- name: reload nfs config
  service: 
    name: nfsserver
    enabled: yes
    state: restarted
  when: exportschanged.changed
  tags: nfs

- name: start and enable nfs
  service: 
    name: nfsserver
    enabled: yes
    state: started
  tags: nfs

