
- name: Install NFS server
  zypper:
    name: nfs-kernel-server
    state: present

- name: Setup /etc/exports
  template: 
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  register: exportschanged

  #- name: Reload NFS config
  #service: 
  #  name: nfsserver
  #  enabled: yes
  #  state: restart
  #  when: exportschanged|changed

- name: Start and Enable NFS
  service: 
    name: nfsserver
    enabled: yes
    state: started

