---
- name: deploy common cluster settings
  hosts:
    - headnode
    - computenodes
  roles:
    - sle_node
    - ntp_client

- name: deploy head node
  hosts:
    - headnode
  roles:
    - head_node
    - slurm_mgr

- name: deploy compute nodes
  hosts:
    - computenodes
  roles:
    - compute_node
    - slurm_node
