- name: Deploy Cluster
  hosts:
    - headnode
    - computenodes
  roles:
    - sle_node
    - ntp_client

- name: Deploy Headnode
  hosts:
    - headnode
  roles:
    - head_node
    - nfs_server

- name: Deploy Computenodes
  hosts:
    - computenodes
  roles:
    - nfs_client

