- name: Deploy Headnode
  hosts:
    - headnode
  roles:
    - sle_node
    - head_node
    #- nfs_server

- name: Deploy Computenodes
  hosts:
    - computenodes
  roles:
    - sle_node
    #- nfs_client

